apiVersion: v1
kind: Namespace
metadata:
  name: s3-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: console-creds
  namespace: s3-demo
type: Opaque
data:
  aws.accessKey: bWluaW8xMjM=
  aws.secretKey: bWluaW8xMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-display
  namespace: s3-demo
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: event-display
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
---
kind: Service
apiVersion: v1
metadata:
  name: event-display
  namespace: s3-demo
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: sources.knative.dev/v1alpha1
kind: IntegrationSource
metadata:
  name: integration-source-aws-s3
  namespace: s3-demo
spec:
  aws:
    s3:
      arn: "arn:aws:s3:::meow-1"
      region: "eu-central-1"
      autoCreateBucket: true
      overrideEndpoint: true
      uriEndpointOverride: "http://minio.minio.svc.cluster.local:9000"
      forcePathStyle: true
    auth:
      secret:
        ref:
          name: "console-creds"
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
