# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ping-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-display
  namespace: ping-demo
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: event-display
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display

---
kind: Service
apiVersion: v1
metadata:
  name: event-display
  namespace: ping-demo
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-demo
  namespace: ping-demo
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Hello World!"}'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display